apiVersion: v1
kind: Service
metadata:
   name: hello-world-deployment
spec:
   ports:
   - port: 5000
     targetPort: 5000
   selector:
     app: hello-world
---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: hello-world-deployment
spec:
   replicas: 1
   selector:
     matchLabels:
       app: hello-world
   template:
     metadata:
       labels:
         app: hello-world
     spec:
       containers:
       - name: hello-world
         image: au.icr.io/hello-world-app/hello-world
         imagePullPolicy: Always
         ports:
         - containerPort: 5000
